server:
  port: ${SERVER_PORT}

spring:
  config:
    activate:
      on-profile: local-docker-cloud
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
            - id: task-service
              uri: lb://task-service
              predicates:
                - Path=/api/v1/tasks/**
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST}:${DISCOVERY_SERVER_PORT}/eureka/
application:
  services:
    auth-service:
      base-uri: http://auth-service
  auth:
    whitelist:
      - /api/v1/auth/sign-in
      - /api/v1/auth/sign-up
      - /api/v1/auth/public-keys/access