server:
  port: ${SPRING_SERVER_PORT}

spring:
  config:
    import: optional:file:./user-service/.env.standalone[.properties]
    activate:
      on-profile: standalone
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false
  flyway:
    default-schema: ${POSTGRES_SCHEMA}
logging:
  level:
    root: INFO