server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:./config-server/.env.native[.properties]
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations/{application}
