spring:
  config:
    import: optional:file:./user-service/.env.standalone[.properties]
    activate:
      on-profile: local-cloud
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: full
          user-service:
            connect-timeout: 6000
            read-timeout: 11000
          task-service:
            connect-timeout: 6000
            read-timeout: 11000
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        delivery.timeout.ms: 20000
        request.timeout.ms: 10000
        linger.ms: 0
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
eureka:
  instance:
    hostname: ${SERVER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_HOST}:${DISCOVERY_SERVER_PORT}/eureka/
    register-with-eureka: true
    fetch-registry: true
application:
  kafka:
    topics:
      email-sending-tasks: ${EMAIL_SENDING_TASKS_TOPIC:EMAIL_SENDING_TASKS}