### Create task using gateway
POST localhost:8222/api/v1/tasks
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNSIsImVtYWlsIjoidXNlcm5hbWVfMTBAZ21haWwuY29tIiwiaWF0IjoxNzU4MDMzNDYxLCJleHAiOjE3NTgwMzUyNjF9.MafkP3Nn0qu46wkeSU6aZPTh4noK_HQvQxaoI9EDGHAIPKU4eQGahT3fpSePK_H-J35uQuZFnOcHvTV8x0kB2CKYgR6HqlPd69kf8t0KajLYS7MbuJQBF6l48JzVqaR9Y65ZHzMvvBATvlSNlInVR62oOkewqi8DWsD8yQKFHQtXfmyjNv1kQcsPjITpzWlAm0731z4ptEfxVk7U5f6jDWYonJ-9dAW4uM04Db-AEW66si4Y5yJI0Q4mCyR3X7WSpn6gP-fyILidZO1uZx2s3_hfRq1oWDdvzjf4Od9zAqXU3j6hEAKzzM9oEq-3WuDxbe0YpQuGUb28hRZUvI74iA
Content-Type: application/json

{
  "title": "First task",
  "description": "Description of first task"
}

### Get tasks by user using gateway
GET localhost:8222/api/v1/tasks
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNyIsImVtYWlsIjoidXNlcm5hbWVfMTJAZ21haWwuY29tIiwiaWF0IjoxNzU4MTg0MDMzLCJleHAiOjE3NTgxODU4MzN9.UZjnbzrRi9hZQyDZJMvPf1iBtndmSDjOPMiljylPqdx_Z4KZqUV97vLVlSOgK_131l6couKKYbX9vbMhHDy7YYVpqEMw1urx2JNKZeKGpSYVhygBemncx685t0E7aB_CkbZnaTRcW3YN6yOq8aQ-OkmQQwoVoi2SJ9wcR1pW9ZqaeJSdUKGB7yGShksauMmgma2H621LGVq-Vvg_MMEzy9NeGofbjC72yeXcL8VpRMy2db8jpp94BIXRLlQJ873WSDVhB1ZgXoQRk2wVj5suCq8Q_ZdNwZ-X2gtigP1HrL5u9jcemwt8KhkaYtiXAa08wzYSzZZg_Mmo4EozBdX7hQ
