### Create task using gateway
POST localhost:8222/api/v1/tasks
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNSIsImVtYWlsIjoidXNlcm5hbWVfMTBAZ21haWwuY29tIiwiaWF0IjoxNzU4MDMzNDYxLCJleHAiOjE3NTgwMzUyNjF9.MafkP3Nn0qu46wkeSU6aZPTh4noK_HQvQxaoI9EDGHAIPKU4eQGahT3fpSePK_H-J35uQuZFnOcHvTV8x0kB2CKYgR6HqlPd69kf8t0KajLYS7MbuJQBF6l48JzVqaR9Y65ZHzMvvBATvlSNlInVR62oOkewqi8DWsD8yQKFHQtXfmyjNv1kQcsPjITpzWlAm0731z4ptEfxVk7U5f6jDWYonJ-9dAW4uM04Db-AEW66si4Y5yJI0Q4mCyR3X7WSpn6gP-fyILidZO1uZx2s3_hfRq1oWDdvzjf4Od9zAqXU3j6hEAKzzM9oEq-3WuDxbe0YpQuGUb28hRZUvI74iA
Content-Type: application/json

{
  "title": "First task",
  "description": "Description of first task"
}

### Get tasks by user using gateway
GET localhost:8222/api/v1/tasks/me
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNSIsImVtYWlsIjoidXNlcm5hbWVfMTBAZ21haWwuY29tIiwiaWF0IjoxNzU4Nzg3MTAzLCJleHAiOjE3NTg3ODg5MDN9.VDT8B60_gGGKhsnpBoppalrwxu4eV9icYy_0qq-_GVTp6z8OECdEjTNQtJwYqbJW8_qIp6DTabATIRLXVWr6ru_Syjw6oUlmGFUt5YP1QxOM57aA5mtX3eShQyIL_ATxnq9Gbo0D1MBlflgjadOOcfcfybh0G2rocZ554vNKtENbG2amIDfY5Fze6PpwLxl8TrFC_zFW6o9aCCE9mWvmEGwTMVtaZtrOkVhHrk_BT-4fiPuQq3DMAUAu8-x1Wfp3QQ7Q6HJBmIyJzawFJFF150Fm3jkSpzExhBn3f_GDaJBHxwToQr_TderaMXWdMuis8YK6A1zjdHjOW0p043Wzww