### GET USER
GET localhost:8081/api/v1/users/2

### POST USER
POST localhost:8081/api/v1/users
Content-Type: application/json

{
  "username": "Username_3",
  "email": "username_3@gmail.com",
  "password": "password"
}

### GET USER USING GATEWAY
GET localhost:8222/api/v1/users/15
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIyNyIsImVtYWlsIjoidXNlcm5hbWVfMTJAZ21haWwuY29tIiwiaWF0IjoxNzU4MDE5MDE4LCJleHAiOjE3NTgwMjA4MTh9.ByZCPCSrdzFVAKIMbJFXR16BFaKuJAjXw7SW80Y0b-2_2CxfnDrDi-mHo8JpkWE4Ioa8dP0ELZm3kFsWy0q1x4GJ1QmZePAM3RKvAVQWdV0XSsZn7nFfNsINVZ4gm2mndyuWxA_9uwUNi9f6gw-kMLtvf6JYf3UWMOGnxGKXM1ypWACd1tDqW5npkgloiY3XqDbWPKEDgtLoySLRGilxaH8KNIIWhW5x3LA_jyps_m9NgjvHj7Tt43dlTzFMco-BU2qRCRKjIzQXRL4atWNtbJvA_8c2_7IMkDZT6MxRudDUK5ay82p2zqWKuz_G5KyuM8FclvRdL25NZxBcIP-APw

### POST USER USING GATEWAY
POST localhost:8222/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZV8xMkBnbWFpbC5jb20iLCJpYXQiOjE3NTc2OTcwNjUsImV4cCI6MTc1NzY5ODg2NX0.BhAQ50CWLxFLGVIHOoH98OE2p7GJBYKhv8khNNgLU6U

{
  "username": "Username_20",
  "email": "username_20@gmail.com",
  "password": "password"
}